# .readthedocs.yaml

version: 2

# Specify the Python environment
python:
  interpreter: python3  # This uses the latest available Python 3 interpreter
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt  # Specify your documentation dependencies

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx conf.py file

# Build system configuration
build:
  os: "ubuntu-22.04"  # Default to Linux-based builds
